yeti/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, include, url

admin.autodiscover()

urlpatterns = patterns('yeti.views.frontend',
    url(r'^$', 'main', name='main'),
    url(r'^asset/(\d+)/$', 'asset', name='asset'),
    url(r'^properties/$', 'properties', name='properties'),
    url(r'^users/$', 'users', name='users'),
)

urlpatterns += patterns('yeti.views.api',
    url(r'^api/asset/(\d+)/outputs/ftp/$', 'asset_ftp_outputs', name='asset_ftp_outputs'),
    url(r'^api/asset/(\d+)/outputs/final/$', 'asset_final_outputs', name='asset_final_outputs'),
    url(r'^api/asset/(\d+)/outputs/$', 'asset_outputs', name='asset_outputs'),
    url(r'^api/asset/(\d+)/task/([\w-]+)/$', 'asset_task_by_name', name='asset_task_by_name'),
    url(r'^api/asset/(\d+)/task/(\d+)/$', 'asset_task', name='asset_task'),
    url(r'^api/asset/(\d+)/tasks/$', 'asset_tasks', name='asset_tasks'),
    url(r'^api/asset/(\d+)/$', 'asset_details', name='asset_details'),
    url(r'^api/asset/$', 'asset', name='asset'),
)

urlpatterns += patterns('yeti.views.docs',
    url(r'^docs/$', 'main', name='docs'),
    url(r'^docs/steps/$', 'steps', name='docs_steps'),
    url(r'^docs/js/$', 'js', name='docs_js'),
)


urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    # r'^media/(?P<path>.*)$
    
    urlpatterns += patterns('',
        url(r'^(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
   )

yeti/models.py
import time
import logging
import os.path

from datetime import datetime
from subprocess import Popen, PIPE

from django.db import models
from django.conf import settings
from django.db.models import Sum
from django.utils import timezone
from django.forms.models import model_to_dict
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType

from yeti.managers import TaskManager, OutputManager

logger = logging.getLogger(__name__)

MEDIA_TYPES = (
    (0, '----'),
    (1, 'Video'),
    (2, 'Image'),
    (3, 'Audio'),
    (4, 'PDF'),
)

class Property(models.Model):
    """
    Property to contain the asset
    """
    name = models.CharField(max_length=75)
    slug = models.CharField(max_length=100)
    storage = models.CharField(max_length=200)
    
    class Meta:
        verbose_name_plural = 'properties'
    
    def __unicode__(self):
        return self.name

class Worker(models.Model):
    hostname = models.CharField(max_length=100, unique=True)

def asset_upload_path(instance, filename):
    """
    Upload path for Asset source
    """
    
    # This ensures the filename is also saved with the Job
    # since Django will rename the file if it exists twice.
    instance.filename = filename
    
    root, ext = os.path.splitext(filename)
    instance.basename = root
    
    logger.debug('Got basename "%s" from filename "%s".', root, filename)
    
    path = os.path.join('src', timezone.now().strftime('%Y/%m/%d'), filename)
    
    logger.debug('Upload path "%s"', path)
    
    return path

class Media(models.Model):
    property = models.ForeignKey(Property, db_index=True)
    
    file = models.CharField(max_length=255)
    
    type = models.PositiveSmallIntegerField(choices=MEDIA_TYPES, default=0)
    
    content_type = models.CharField(max_length=50, blank=True)
    filename = models.CharField(max_length=100, blank=True)
    basename = models.CharField(max_length=100, blank=True)
    extension = models.CharField(max_length=10, blank=True)
    size = models.PositiveIntegerField(blank=True, null=True)
    
    created = models.DateTimeField(auto_now_add=True)
    
    width = models.PositiveSmallIntegerField(null=True, blank=True)
    height = models.PositiveSmallIntegerField(null=True, blank=True)
    
    duration = models.PositiveIntegerField(null=True, blank=True, help_text='in milliseconds')
    bit_rate = models.PositiveIntegerField(null=True, blank=True)
    container_format = models.CharField(max_length=100, blank=True)
    
    sar = models.CharField(max_length=100, blank=True)
    dar = models.CharField(max_length=100, blank=True)
    
    video_codec = models.CharField(max_length=100, blank=True)
    video_bit_rate = models.PositiveIntegerField(null=True, blank=True)
    video_frame_rate = models.CharField(max_length=100, blank=True)
    
    audio_codec = models.CharField(max_length=100, blank=True)
    audio_bit_rate = models.PositiveIntegerField(null=True, blank=True)
    audio_channels = models.PositiveSmallIntegerField(null=True, blank=True)
    audio_sample_rate = models.PositiveIntegerField(null=True, blank=True)
    
    probe_output = models.TextField(blank=True)
    
    class Meta:
        abstract = True

class Scenario(models.Model):
    name = models.CharField(max_length=100)
    property = models.ForeignKey(Property)
    steps = models.TextField()
    
    date_added = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    
    class Meta:
        unique_together = ('name', 'property')

class Asset(Media):
    title = models.CharField(max_length=150, blank=True)
    slug = models.CharField(max_length=200, blank=True)
    
    field_name = models.CharField(max_length=100)
    
    url = models.URLField(blank=True)
    
    scenario = models.ForeignKey(Scenario, blank=True, null=True)
    
    progress = models.PositiveSmallIntegerField(default=0)
    status = models.CharField(max_length=100, blank=True)
    
    is_test = models.BooleanField(default=False)
    
    @models.permalink
    def get_absolute_url(self):
        return ('yeti.views.frontend.asset', [str(self.id)])
    
    def get_working_path(self):
        """
        If the file exists on the transcoder, return the media path.
        Otherwise, we are assuming it's an absolute path.
        """
        return self.file
    
    def get_input_location(self):
        """
        Determine the location of the input media. URL or file based.
        """
        if self.url:
            return self.url
        else:
            return self.file
    
    def get_progress(self):
        if self.status in ('failed','stopped','completed'):
            return 100
        elif self.status in ('created', 'started'):
            return 0
        else:        
            return self.progress
    
    def check_completion(self):
        states = set(Task.objects.filter(asset=self).values_list('status', flat=True))
        
        if len(states) == 1 and 'completed' in states:
            self.status = 'completed'
        elif 'failed' in states:
            self.status = 'failed'
        
        self.save(update_fields=['status'])
    
    def tasks(self):
        for task in Task.objects.filter(asset=self, parent=None):
            ttype = getattr(task, task.content_type.model)
    
    def serialize(self):
        fields = ('id', 'title', 'slug', 'content_type',
                  'filename', 'basename', 'size', 'created')
        obj = {}
        for field in fields:
            value = getattr(self, field)
            if isinstance(value, datetime):
                value = value.isoformat()
            obj[field] = value
        obj['type'] = self.get_type_display()
        return obj
    
    def admin_property(self):
        """
        Return the property name
        """
        
        return self.property.name
    
    admin_property.short_description = 'property'
    admin_property.admin_order_field = 'property__name'
    
    def progress_class(self):
        if self.status in ('failed',):
            return 'progress progress-danger'
        elif self.status in ('dependent', 'stopped', 'retrying'):
            return 'progress progress-warning'
        elif self.progress == 100 or self.status in ('completed',):
            return 'progress progress-success'
        else:
            return 'progress progress-striped active'
    
    def full_path(self):
        """
        A convenience method to return the path of the file, which
        would depend on whether it's saved as a path or a file.
        """
        return self.path if self.path else self.file.path
    
    def total_progress(self):
        count = self.task_set.count()
        total = self.task_set.aggregate(total=Sum('progress'))['total'] or 0
        
        try:
            percentage = int(float(total) / count)
        except ZeroDivisionError:
            percentage = 0
        
        if self.progress != percentage:
            self.progress = percentage
            self.save(update_fields=['progress'])
        
        logger.debug('Total progress: "%d%%"', percentage)
        
        return percentage

class Task(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True)
    asset = models.ForeignKey(Asset)
    name = models.CharField(max_length=100)
    process = models.CharField(max_length=100)
    parameters = models.TextField()
    progress = models.PositiveSmallIntegerField(default=0)
    speed = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    
    hostname = models.CharField(max_length=100)
    
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    
    time = models.PositiveIntegerField(null=True, blank=True)
    utime = models.PositiveIntegerField(null=True, blank=True)
    
    error_message = models.TextField(blank=True)
    
    status = models.CharField(max_length=100, default='created')
    amqp_id = models.CharField(max_length=100)
    
    objects = TaskManager()
    
    def save(self, *args, **kwargs):
        # progress can not be greater than 100
        self.progress = min(self.progress, 100)
        super(Task, self).save(*args, **kwargs)
    
    def fail(self, message='', status='failed'):
        self.asset.status = status
        self.asset.save(update_fields=['status'])
        
        def fail_task(task):
            task.status = status
            task.progress = 100
            task.error_message = message.rstrip('.')
            task.save(update_fields=['status', 'progress', 'error_message'])
            
            for child in Task.objects.filter(parent=task):
                fail_task(child)
        
        fail_task(self)
    
    def complete(self, time=None, utime=None):
        update_fields = ['progress', 'status', 'end_date']
        
        self.progress = 100
        self.status = 'completed'
        self.end_date = timezone.now()
        
        if time:
            self.time = time
            update_fields.append('time')
        
        if utime:
            self.utime = utime
            update_fields.append('utime')
        
        self.save(update_fields=update_fields)
    
    def get_display_class(self):
        if self.status in ('failed',):
            return 'danger'
        elif self.status in ('dependent', 'stopped', 'waiting', 'retrying'):
            return 'warning'
        elif self.status in ('completed',):
            return 'success'
        else:
            return 'striped active'
    
    def get_progress(self):
        if self.status in ('failed','stopped','completed'):
            return 100
        elif self.status in ('created', 'started'):
            return 0
        else:        
            return self.progress
    
    def progress_class(self):
        if self.status in ('failed',):
            return 'progress progress-danger'

yeti/views/control.py
import logging

from celery.task.control import revoke

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from yeti.models import Task

logger = logging.getLogger(__name__)

@csrf_exempt
def stop_job(request, id):
    task = Task.objects.get(pk=id)
    
    task_id = request.POST.get('task_id')
    
    if task_id == task.amqp_id:
        revoke(task_id, terminate=True)
        
        task.status = 'stopped'
        task.save(update_fields=['status'])
    
    return HttpResponse()

yeti/views/docs.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.sites.models import Site, get_current_site
from django.db.models import Q

def main(request):
    current_site = get_current_site(request)
    
    released = Q(domain__contains='yeti.turner.com')
    current = Q(pk=current_site.id)
    
    sites = Site.objects.filter(released | current).order_by('id')
    
    return render(request, 'docs/main.html', {
        'sites': sites,
        'current_site': current_site,
    })

def steps(request):
    current_site = get_current_site(request)
    
    return render(request, 'docs/steps.html', {
        'current_site': current_site,
    })

def js(request):
    current_site = get_current_site(request)
    
    return render(request, 'docs/javascript.html', {
        'current_site': current_site,
    })

yeti/views/frontend.py
import logging

from django.shortcuts import render

from yeti.models import Asset

logger = logging.getLogger(__name__)

def main(request):
    """
    This displays the list of the assets in the system.
    """
    
    page = int(request.GET.get('page', 1))
    size = min(int(request.GET.get('size', 10)), 100) # maximum of 100
    
    total = Asset.objects.count()
    
    from math import ceil
    
    numpages = int(ceil(total / float(size)))
    
    page = max(page, 1)
    
    offset = (page - 1) * size
    end = offset + size
    
    assets = Asset.objects.select_related().order_by('-id')[offset:end]
        
    if numpages <= 10:
        pages = range(1, numpages + 1)
    else:
        if page >= numpages - 4:
            start = numpages - 9
        else:
            start = max(1, page - 5)
        
        if numpages > 10 and page <= 6:
            end = 11
        else:
            end = min(page + 5, numpages + 1)
        
        pages = range(start, end)
    
    return render(request, 'yeti/list.html', {'assets': assets, 'current': page, 'pages': pages, 'size': size})

def asset(request, id):
    """
    Display tasks associated with an Asset.    
    """
    
    asset = Asset.objects.select_related().get(id=id)
    
    tasks = []
    
    from yeti.models import Task
    
    def flatten_tasks(task):
        for t in Task.objects.filter(asset=asset, parent=task):
            tasks.append(t)
            flatten_tasks(t)
    
    flatten_tasks(None)
    
    return render(request, 'yeti/asset.html', {'asset': asset, 'tasks': tasks})

def properties(request):
    """
    Display a list of the properties in the system.
    """
    
    from yeti.models import Property
    
    properties = Property.objects.all()
    
    return render(request, 'yeti/properties.html', {'properties': properties})

def users(request):
    """
    Display a list of users in the system.
    """
    
    from django.contrib.auth.models import User
    
    users = User.objects.all()
    
    return render(request, 'yeti/users.html', {'users': users})

yeti/templates/yeti/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Yeti</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 80px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
	  @media (max-width: 980px) {
	  .navbar-text.pull-right {
	    float: none;
	    padding-left: 5px;
	    padding-right: 5px;
	  }
	}
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/custom.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="{{ STATIC_URL }}js/html5shiv.min.js"></script>
    <![endif]-->
    
    {% block extra_stylesheet %}{% endblock %}
    
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="{% block container_type %}container{% endblock %}">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><img src="{{ STATIC_URL }}img/yeti-90.png"></a>
        </div>
      </div>
    </div>

    {% block container %}<div class="container">{% block body %}{% endblock %}</div>{% endblock %}
    
    <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/application.js"></script>
    
    {% block javascript %}{% endblock %}
  </body>
</html>

yeti/templates/yeti/encoding.html
{% extends "yeti/sidebar.html" %}

{% block encode_asset_active %} class="active"{% endblock %}

{% block body %}

<div class="page-header">
  <h1>Encode an Asset</h1>
</div>



<form class="form-horizontal" id="myForm">
  

  <div class="tabbable tabs-left">
    
    <ul class="nav nav-tabs" id="myTab">
      <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
      <li><a href="#input" data-toggle="tab">Input</a></li>
      <li><a href="#transcoding" data-toggle="tab">Transcoding</a></li>
      <li><a href="#publishing" data-toggle="tab">Publishing</a></li>
    </ul>
    
    <div class="tab-content">
    
    
      <div class="tab-pane active" id="details">
        <fieldset>
          <div class="control-group">
            <label class="control-label" for="input01">Title</label>
            <div class="controls">
              <input type="text" class="input-large" id="id_title" data-key="title">
            </div>
          </div>
    
          <div class="control-group">
            <label class="control-label" for="input01">Slug</label>
            <div class="controls">
              <input type="text" class="input-large" id="id_slug" data-key="slug">
            </div>
          </div>
    
          <div class="control-group">
            <label class="control-label" for="select01">Property</label>
            <div class="controls">
              <select id="id_property" data-key="property">
                <option value="">Choose a value…</option>
                {% for property in properties %}
                <option value="{{ property.slug }}">{{ property.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </fieldset>
      </div>

      <div class="tab-pane" id="input">
        <fieldset>
          <div class="alert alert-info">
            <button class="close" data-dismiss="alert">×</button>
            <strong>Warning!</strong> You can only choose one of the following.
          </div>
      
      
          <div class="control-group">
            <label class="control-label" for="input01">File</label>
            <div class="controls">
              <input type="file" class="input-file" id="id_file">
            </div>
          </div>
      
          <div class="control-group">
            <label class="control-label" for="input01">Input URL</label>
            <div class="controls">
              <input type="url" class="input-xlarge" id="id_input_url">
              <p class="help-block">http://, ftp:// or sftp://</p>
            </div>
          </div>
      
        </fieldset>
      </div>
   
     <div class="tab-pane" id="transcoding">
        <div class="btn-group">
          <button class="btn" id="add-video"><i class="icon-facetime-video"></i> Add video</a></button>
          <button class="btn" id="add-image"><i class="icon-picture"></i> Add image</a></button>
        </div>
        <br>
        <fieldset>
          <legend>Container</legend>
          <div class="control-group">
            <label class="control-label" for="input01">Format</label>
            <div class="controls">
              <select id="">
                <option value="mov">QuickTime / MPEG-4</option>
                <option value="m4v">Raw MPEG-4 (.m4v)</option>
                <option value="mpegts">MPEG-2 Transport Stream</option>
                <option value="flv">FLV Format</option>
                <option value="webm">WebM</option>
                <option value="matroska">Matroska</option>
              </select>
            </div>
          </div>
        </fieldset>
        
        <fieldset>
          <legend>Video</legend>
          <div class="control-group">
            <label class="control-label" for="input01">Codec</label>
            <div class="controls">
              <select id="" class="input-small">
                <option value="libx264">H.264</option>
                <option value="libvpx">VP8</option>
                <option value="mpeg2video">MPEG-2</option>
              </select>
            </div>
          </div>
          
          <div class="control-group">
            <label class="control-label" for="input01">Width</label>
            <div class="controls">
              <div class="input-append">
                <input id="appendedInput" size="16" type="text" class="input-mini" ><span class="add-on">px</span>
              </div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="input01">Height</label>
            <div class="controls">
              <div class="input-append">
                <input id="appendedInput" size="16" type="text" class="input-mini" ><span class="add-on">px</span>
              </div>
            </div>
          </div>
          
          <div class="control-group">
            <label class="control-label" for="input01">Bitrate</label>
            <div class="controls">
              <div class="input-append">
                <input id="appendedInput" size="16" type="text" class="input-mini" ><span class="add-on">kbps</span>
              </div>
            </div>
          </div>
        </fieldset>
        
        <fieldset>
          <legend>Audio</legend>
          <div class="control-group">
            <label class="control-label" for="input01">Codec</label>
            <div class="controls">
              <select id="" class="input-small">
                <option value="libfaac">AAC</option>
                <option value="libmp3lame">MP3</option>
                <option value="libvorbis">Vorbis</option>
                <option value="ac3">AC-3</option>
                <option value="pcm_s16le">PCM 16-bit</option>
              </select>
            </div>
          </div>
          
          <div class="control-group">
            <label class="control-label" for="input01">Bitrate</label>
            <div class="controls">
              <div class="input-append">
                <input id="appendedInput" size="16" type="text" class="input-mini" ><span class="add-on">kbps</span>
              </div>
            </div>
          </div>
        </fieldset>
        
        </fieldset>
      </div>
  
      <div class="tab-pane" id="publishing">
        <fieldset>
          <div class="control-group">
            <label class="control-label" for="input01">Publish URL</label>
            <div class="controls">
              <input type="url" class="input-xlarge" id="input01">
              <p class="help-block">http://, ftp:// or sftp://</p>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="optionsCheckbox">Verify</label>
            <div class="controls">
              <label class="checkbox">
                <input type="checkbox" id="optionsCheckbox" value="option1">
                Check that the media made it to it's destination, pulling it through HTTP.
              </label>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="input01">Verify URL</label>
            <div class="controls">
              <input type="url" class="input-xlarge" id="input01">
            </div>
          </div>
      
      
  
        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Save changes</button>
          <button class="btn">Cancel</button>
        </div>
        </fieldset>
      </div>
      
      
      
    </div>
  </div>
</form>


<pre id="jsonOutput">{}</pre>
{% endblock %}

{% block javascript %}
<script src="{{ STATIC_URL }}js/json2.js"></script>
<script>


$(function () {
  var json = {},
      jsonOutput = $("#jsonOutput");
  
  function updateJSON() {
    jsonOutput.text(JSON.stringify(json));
  }
  
  function changeValue(elem) {
    if (elem.val()) {
      json[elem.data('key')] = elem.val();
    } else {
      delete json[elem.data('key')];
    }
    
    updateJSON();
  }
  
  var slug_words = Array('at', 'but', 'by', 'down', 'from', 'in', 'into', 'like', 'near', 'of', 'off', 'on', 'onto', 'over', 'past', 'till', 'to', 'up', 'upon', 'with', 'and', 'or', 'nor', 'for', 'so', 'yet', 'for');
  
  function slugify(value) {
    var slug = value.replace('\'', '').replace(/[^a-zA-Z0-9]+/g,'-').toLowerCase();
    var words = slug.split('-'), new_set = Array();
    
    
    for (var i=0; i < words.length; i++) 
    {
      var word = words[i];
      if (slug_words.indexOf(word) == -1) {
        new_set.push(word);
      }
    }
    
    return new_set.join('-');
  }
  
  $("#id_title").keyup(function () {
    var $this = $(this);
    var $slug = $("#id_slug");
    var slug = slugify($this.val());
    
    $slug.val(slug);
    
    changeValue($this);
    changeValue($slug);
  });
  
  $("#id_slug").keyup(function () {
    var $this = $(this);
    var slug = slugify($this.val());
    
    $this.val(slug);
    
    changeValue($this);
  });
  
  $("#id_slug").blur(function () {
    var $this = $(this);
    
    $this.val($this.val().replace(/\-+$/, ''));
  });
  
  $("#id_property").change(function () {
    console.log($(this).val());
    changeValue($(this));
  });
  
  
  // $("#id_title").keyup(function () {
  //   
  //   var $this = $(this);
  //   
  //   console.log($this.val());
  //   console.log($this.data('key'));
  //   
  //   // json[$this.data('key')] = $this.val();
  //   
  //   json.title = $(this).val();
  //   updateJSON();
  // });
  // 
  // $("#id_slug").keyup(function () {
  //   json.slug = $(this).val();
  //   updateJSON();
  // });
    
    
    $('#id_title').popover({title: 'Title', content:'Specify your title (in title case, of course). <br><br>e.g. Greeks Divided on Euro Austerity Demands'});
    $('#id_slug').popover({title: 'Slug', content:'A <a href="http://en.wikipedia.org/wiki/Slug_(web_publishing)">slug</a> is usually the title converted to a URL safe version by making it all lowercase, replacing spaces and other punctuation with a hypen, and removing unnecssary prepositions. <br><br>e.g. greeks-divided-euro-austerity-demands'});
    
    var $id_file = $("#id_file"), 
        $id_input_url = $("#id_input_url");
    
    $id_file.bind('change keyup', function () {
      
      
      if ($id_input_url.val() && $id_file.val()) {
        $id_file.closest('.control-group').addClass('error');
        $(".alert").removeClass('alert-info').addClass('alert-error');
      } else {
        $id_input_url.closest('.control-group').removeClass('error');
        $(".alert").removeClass('alert-error').addClass('alert-info');
      }
    });
    
    $id_input_url.bind('change keyup', function () {
      if ($id_file.val() && $id_input_url.val()) {
        $id_input_url.closest('.control-group').addClass('error');
        $(".alert").removeClass('alert-info').addClass('alert-error');
      } else {
        $id_input_url.closest('.control-group').removeClass('error');
        $(".alert").removeClass('alert-error').addClass('alert-info');
      }
    });
    
    $("#add-video").click(function (event) {
      event.preventDefault();
      
    });
    
    $("#add-image").click(function (event) {
      event.preventDefault();
      
    })
    
});
</script>
{% endblock %}

yeti/templates/yeti/main.html
{% extends "yeti/base.html" %}

{% block body %}

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>VPS Transcode Engine</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Heading</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2012 Turner Broadcasting System, Inc.</p>
      </footer>

{% endblock %}